---
version: "3.3"

services:
  sea-eos-1:
    hostname: sea-eos-1
    container_name: sea-eos-1
    privileged: true
    image: vr-veos:4.22.1F
    networks:
      net1:
        ipv4_address: 172.18.0.11

  sea-nxos-1:
    hostname: sea-nxos-1
    container_name: sea-nxos-1
    privileged: true
    image: vr-n9kv:9.2.4
    networks:
      net1:
        ipv4_address: 172.18.0.12

  vr-xcon:
    hostname: vr-xcon
    privileged: true
    image: vr-xcon:1.0
    command: "--p2p sea-eos-1/2--sea-nxos-1/1 sea-eos-1/3--sea-nxos-1/2"
    networks:
      net1:
        ipv4_address: 172.18.0.10

networks:
  net1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/26
